version: '3.9'

services:
  postgres-omnia:
    image: postgres:15-alpine
    container_name: postgres-omnia
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /Users/kokohbudi/docker_data/postgres-data:/var/lib/postgresql/data
    networks:
      - ${NETWORK}

  keycloak-omnia:
    image: quay.io/keycloak/keycloak:26.2.1
    container_name: keycloak-omnia
    command: start-dev
    ports:
      - "9999:8080"
    environment:
      KC_FEATURES: organization
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-omnia
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: kozaninja
    depends_on:
      - postgres-omnia
    networks:
      - ${NETWORK}
    volumes:
      - /Users/kokohbudi/docker_data/keycloak-themes:/opt/keycloak/themes


networks:
  omnia-network:
    name: ${NETWORK}
