
services:
  keycloak-satset:
    image: quay.io/keycloak/keycloak:26.2.1
    container_name: keycloak-satset
    command: start-dev
    ports:
      - "9999:8080"
    environment:
      KC_FEATURES: organization
      KC_DB: postgres
      KC_DB_URL_HOST: ${KC_NEON_HOST}
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KC_NEON_DB}
      KC_DB_SCHEMA: ${KC_NEON_SCHEMA}
      KC_DB_URL_PROPERTIES: ${DB_URL_PROPERTIES}
      KC_DB_USERNAME: ${KC_NEON_USER}
      KC_DB_PASSWORD: ${KC_NEON_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - ${NETWORK}
    volumes:
      - /Users/kokohbudi/docker_data/keycloak-themes:/opt/keycloak/themes


networks:
  satset-network:
    name: ${NETWORK}
