
services:
  postgres-satset:
    image: postgres:15-alpine
    container_name: postgres-satset
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /Users/kokohbudi/docker_data/postgres-data:/var/lib/postgresql/data
    networks:
      - ${NETWORK}

  keycloak-satset:
    image: quay.io/keycloak/keycloak:26.2.1
    container_name: keycloak-satset
    command: start-dev
    ports:
      - "9999:8080"
    environment:
      KC_FEATURES: organization
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-satset
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - postgres-satset
    networks:
      - ${NETWORK}
    volumes:
      - /Users/kokohbudi/docker_data/keycloak-themes:/opt/keycloak/themes


networks:
  satset-network:
    name: ${NETWORK}
