name: 📌 Task
description: Task kecil yang harus diselesaikan
title: "[TASK] "
labels: [task]
assignees: [kokohbudi]

body:
  - type: textarea
    id: task-desc
    attributes:
      label: Deskripsi Task
      description: Jelaskan tugas ini secara singkat
      placeholder: "Misalnya: Validasi agar email wajib format @ dan tidak kosong."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Prioritas
      options:
        - High - Tinggi
        - Medium - Sedang
        - Low - Rendah
